run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
  disable:
    - typecheck
    - depguard

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - fmt.Fprint
      - fmt.Fprintln
      - fmt.Fprintf

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: cmd/
      linters:
        - errcheck
    - path: internal/storage/redis\.go
      linters:
        - typecheck
    - path: internal/kafka/kafka\.go
      linters:
        - typecheck
  max-issues-per-linter: 0
  max-same-issues: 0
